### ISSUE TITLE
Suggest you no longer special case lttng in your dependencies setup

### ISSUE THREAD

**Issue by MatthewMWR** [microsoft/tracelogging#20]
The 2.10 version of lttng library is no longer experimental. In fact as of today 2.11 is available and installed by default from mainstream places like ubuntu package repos. For example on a vanilla Ubuntu device I see the following:

(note I am not running add-repository first)
```
$ sudo apt install liblttng-ust-dev

$ sudo apt show liblttng-ust-dev
Package: liblttng-ust-dev
Version: 2.11.0-1
```

Accordingly my proposal is you should drop the add-repository step from your instructions, for three reasons:
* Simplicity
* Keep up with bug fixes in lttng
* the unnecessary add-repository step results in a system-wide degradation (depending on your point of view), in that it results in security warning every time your run apt update, etc.

**Comment by idigdoug** [comment]
Updated the readme, should be more clear now.
