### ISSUE TITLE
Support for C++ STL types in tracelogging?

### ISSUE THREAD

**Issue by jonwis** [microsoft/tracelogging#60]
I'd like to add support for `std::[w]string[_view]` and a related type `winrt::hstring` ... I put together https://github.com/jonwis/jonwis.github.io/tree/in-progress/code/TlgAutoTest as a header on top of the existing `TraceLoggingProvider.h` for C++.

Is http://github.com/microsoft/wil a better place to put this kind of helper?

**Comment by idigdoug** [comment]
I can't support extensibility for TraceLoggingValue in a safe way.

It might be possible to add a new macro to the TraceLoggingProvider.h header, maybe like TraceLoggingCppString(str) that works with contiguous-container-of-CHARnn (anything with a data() and a size(), accepts char, wchar, char8, char16, char32), or TraceLoggingCppArray(vec) that works with contiguous-container-of-T (anything with a data() and a size(), accepts similar set of T as TraceLoggingValue but does not accept char*).
